### ISSUE TITLE
Confirmed to work on 14" M1 MBP + BetterDisplay implementation?

### ISSUE THREAD

**Issue by waydabber** [aiaf/Stillcolor#1]
Hi there,

just wanted to confirm that this works with the M1 MBP as well (tested on a 14" MBP with M1 Pro). Works well on a 16" M3 Max too.

I was trying to use various IOMobileFramebuffer stuff in the past (some working, some not), the only actual useful thing came out of it was inverting the screen and turning it to grayscale https://github.com/waydabber/BetterDisplay/issues/2745

Is it ok with you if I add a toggle for temporal dithering in BetterDisplay for built-in screens using this method in the next app version?

https://github.com/waydabber/BetterDisplay/wiki/Eye-care:-prevent-PWM-and-or-temporal-dithering

Thank you!

(ps. an user pointed me to your project here: https://github.com/waydabber/BetterDisplay/discussions/1201)

**Comment by waydabber** [comment]
Oh ok, I am just reading the ledstrain.org discussion and see various M1 MBPs working have been confirmed already, so this is not news + I see the project is MIT licensed and the method itself quite generic so my question probably does not make much sense. :) Sorry.

Anyway, great finding, thanks for all you are doing! 👍

**Comment by aiaf** [comment]
It's been confirmed to work with various configurations, I've personally tested it on M2 and M3.

Absolutely go ahead, as you mentioned, the project is MIT licensed :)
 
I use BetterDisplay, and previously Monitor Control. It would be nice to have a dynamic per-display control over DCP dithering.

Funnily enough I was testing the `BlendOutputCSCMethod` property today and it inverted the colors on the screen.

Which property did you use to toggle grayscale? I can't see the options when I option+click Image Adjustments.

I'm now focusing my efforts on trying to disable TCON-controlled (reverse temporal) dithering, and perhaps forcing a lower bit depth on the internal display, which is proving to be really challenging.
