### ISSUE TITLE
Please make Stillcolor Sequoia compatible

### ISSUE THREAD

**Issue by tunhovd** [aiaf/Stillcolor#13]
Just installed Mac Sequoia and Stillcolor stopped working. 

Guess you are on it already. If not, now you know :)

Kind regards, Audun

**Comment by aiaf** [comment]
Hey @tunhovd - what is exactly the error you're seeing? Does the app not launch at all? Or does it run but menu options don't function? 

I'm not sure I will install Sequoia anytime soon so I appreciate the additional context. I've read that Sequoia has a stricter Gatekeeper and permission system.

**Comment by tunhovd** [comment]
My apologies. I did not see the program running. 

After I installed the latest MacOs I thought Stillcolor was not running, (freaked out), and wrote a message at your forum. 

It’s all good. Please feel free to delete this thread.

Kind regards, Audun

**Comment by aiaf** [comment]
No worries, thanks!
