### ISSUE TITLE
Add Uniformity2D Option

### ISSUE THREAD

**Issue by chunqian** [aiaf/Stillcolor#4]
Thank you so much for your contribution, it has restored my eyes. Can you release the option for adding uniformity2D? I really need disable uniformity2D option, and I would be very willing to pay for it because it has saved my eyes!

**Comment by aiaf** [comment]
Glad it helped you out! It will be added in the upcoming update- code is ready just need to review and push

**Comment by chunqian** [comment]
Great, thanks again for your outstanding contribution!

**Comment by aiaf** [comment]
Please check the latest release, added option to disable `uniformity2D` https://github.com/aiaf/Stillcolor/releases/latest

**Comment by chunqian** [comment]
It works! 
I will turn off enableDither and uniformity2D today to use macbook air 15 m3 for a whole day, the moment I turn off enableDither and uniformity2D, the screen looks so cool!

**Comment by chunqian** [comment]
@aiaf 
Thank you for your efforts!

**Comment by aiaf** [comment]
Thanks, appreciate your feedback!
