### ISSUE TITLE
Does Stilcolor interfere with F.lux? OK to run them side-by-side?

### ISSUE THREAD

**Issue by zenminimalist** [aiaf/Stillcolor#6]
Thanks for providing such a handy utility! 

Just a quick question:
I'm a big fan of [flux](https://justgetflux.com/news/pages/macquickstart/). Does Stilcolor in any way interfere with it or the other way around? 

Sorry, I'm not that technical to answer that question myself.

**Comment by aiaf** [comment]
It shouldn't interfere. Stillcolor does 1 thing only by default which is disable the enableDither property on the display driver.
